### ISSUE TITLE
Prace

### ISSUE THREAD

**Issue by Hawthorne001** [microsoft/prose#77]
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/prose/issues/72
- [ ] https://github.com/microsoft/prose/issues/76
- [ ] https://github.com/microsoft/prose/pull/75
- [ ] https://github.com/microsoft/prose/pull/74
- [ ] https://github.com/microsoft/prose/pull/73
- [ ] https://github.com/microsoft/prose/pull/71
- [ ] https://github.com/microsoft/prose/pull/70
- [ ] https://github.com/microsoft/prose/pull/69
- [ ] https://github.com/microsoft/prose/pull/68
- [x] Build MainH
```
